[CNM-5147] replace simplelru.LRU with lru.Cache  (#46886)
### What does this PR do?
`simplelru.LRU` is not thread safe and has been causing panic errors in system probe
```
fatal error: concurrent map read and map write
```
Looking at a [commit](https://github.com/DataDog/datadog-agent/pull/46741) in CWS cgroup resolver it seems like they had a similar issue with the simplelru package and resulted in using the more thread safe [LRU cache](https://github.com/hashicorp/golang-lru/blob/5015efc0ee404341dc6567691cf384a0075cac7d/lru.go#L18) which handles mutexes internally to prevent these concurrent map read/writes

### Motivation
https://datadoghq.atlassian.net/browse/CNM-5147

### Describe how you validated your changes
Ran the gateway lookup tests locally on an arm64 vagrant VM following the [Local Development docs](https://datadoghq.atlassian.net/wiki/spaces/EBPF/pages/3035661445/Local+Development#Building-the-System-Probe)

```
dda inv -e system-probe.test -p ./pkg/network/tracer/ -r "TestTracerSuite/.*/TestGatewayLookup"
```

All four tests pass across `runtime_compiled`, `CO-RE`, and `eBPFless` build modes

<details>
<summary>Test summary</summary>

```
--- PASS: TestTracerSuite (17.18s)
    --- PASS: TestTracerSuite/runtime_compiled (8.03s)
        --- PASS: TestTracerSuite/runtime_compiled/TestGatewayLookupCrossNamespace (1.55s)
            --- PASS: TestTracerSuite/runtime_compiled/TestGatewayLookupCrossNamespace/client_in_root_namespace (0.00s)
            --- PASS: TestTracerSuite/runtime_compiled/TestGatewayLookupCrossNamespace/client_in_other_namespace (0.05s)
        --- PASS: TestTracerSuite/runtime_compiled/TestGatewayLookupEnabled (2.64s)
            --- PASS: TestTracerSuite/runtime_compiled/TestGatewayLookupEnabled/aws_ec2 (1.30s)
            --- PASS: TestTracerSuite/runtime_compiled/TestGatewayLookupEnabled/aws_fargate (1.35s)
        --- PASS: TestTracerSuite/runtime_compiled/TestGatewayLookupNotEnabled (2.53s)
            --- PASS: TestTracerSuite/runtime_compiled/TestGatewayLookupNotEnabled/gateway_lookup_enabled,_not_on_aws (1.24s)
            --- PASS: TestTracerSuite/runtime_compiled/TestGatewayLookupNotEnabled/gateway_lookup_enabled,_aws_metadata_endpoint_not_enabled (1.29s)
        --- PASS: TestTracerSuite/runtime_compiled/TestGatewayLookupSubnetLookupError (1.31s)
    --- PASS: TestTracerSuite/CO-RE (8.09s)
        --- PASS: TestTracerSuite/CO-RE/TestGatewayLookupCrossNamespace (1.46s)
            --- PASS: TestTracerSuite/CO-RE/TestGatewayLookupCrossNamespace/client_in_root_namespace (0.00s)
            --- PASS: TestTracerSuite/CO-RE/TestGatewayLookupCrossNamespace/client_in_other_namespace (0.04s)
        --- PASS: TestTracerSuite/CO-RE/TestGatewayLookupEnabled (2.72s)
            --- PASS: TestTracerSuite/CO-RE/TestGatewayLookupEnabled/aws_ec2 (1.43s)
            --- PASS: TestTracerSuite/CO-RE/TestGatewayLookupEnabled/aws_fargate (1.28s)
        --- PASS: TestTracerSuite/CO-RE/TestGatewayLookupNotEnabled (2.48s)
            --- PASS: TestTracerSuite/CO-RE/TestGatewayLookupNotEnabled/gateway_lookup_enabled,_not_on_aws (1.25s)
            --- PASS: TestTracerSuite/CO-RE/TestGatewayLookupNotEnabled/gateway_lookup_enabled,_aws_metadata_endpoint_not_enabled (1.23s)
        --- PASS: TestTracerSuite/CO-RE/TestGatewayLookupSubnetLookupError (1.43s)
    --- PASS: TestTracerSuite/eBPFless (1.05s)
        --- PASS: TestTracerSuite/eBPFless/TestGatewayLookupCrossNamespace (0.34s)
            --- PASS: TestTracerSuite/eBPFless/TestGatewayLookupCrossNamespace/client_in_root_namespace (0.10s)
            --- SKIP: TestTracerSuite/eBPFless/TestGatewayLookupCrossNamespace/client_in_other_namespace (0.00s)
        --- PASS: TestTracerSuite/eBPFless/TestGatewayLookupEnabled (0.31s)
            --- PASS: TestTracerSuite/eBPFless/TestGatewayLookupEnabled/aws_ec2 (0.18s)
            --- PASS: TestTracerSuite/eBPFless/TestGatewayLookupEnabled/aws_fargate (0.13s)
        --- PASS: TestTracerSuite/eBPFless/TestGatewayLookupNotEnabled (0.17s)
            --- PASS: TestTracerSuite/eBPFless/TestGatewayLookupNotEnabled/gateway_lookup_enabled,_not_on_aws (0.08s)
            --- PASS: TestTracerSuite/eBPFless/TestGatewayLookupNotEnabled/gateway_lookup_enabled,_aws_metadata_endpoint_not_enabled (0.09s)
        --- PASS: TestTracerSuite/eBPFless/TestGatewayLookupSubnetLookupError (0.22s)
PASS
ok      github.com/DataDog/datadog-agent/pkg/network/tracer     17.224s           
  ```
</details>      


Co-authored-by: janae.quinones <janae.quinones@datadoghq.com>