Disable gazelle proto generation for all external deps (#50166)
### What does this PR do?

Adds directive to disable proto generation when gazelle generates build files for external dependencies.

### Motivation

I hit this error while adding another default directive while migrating a bunch of packages:

```
ERROR: no such package '@@gazelle++go_deps+io_k8s_apimachinery//k8s.io/apimachinery/pkg/runtime/schema': BUILD file not found in directory 'k8s.io/apimachinery/pkg/runtime/schema' of external repository @@gazelle++go_deps+io_k8s_apimachinery. Add a BUILD file to a directory to mark it as a package.
ERROR: /Users/alex.lopez/Library/Caches/bazel/_bazel_alex.lopez/7a4d107c5f8bd1c8a832a90593fd2c47/external/gazelle++go_deps+io_k8s_apimachinery/pkg/apis/meta/v1/BUILD.bazel:15:17: no such package '@@gazelle++go_deps+io_k8s_apimachinery//k8s.io/apimachinery/pkg/runtime/schema': BUILD file not found in directory 'k8s.io/apimachinery/pkg/runtime/schema' of external repository @@gazelle++go_deps+io_k8s_apimachinery. Add a BUILD file to a directory to mark it as a package. and referenced by '@@gazelle++go_deps+io_k8s_apimachinery//pkg/apis/meta/v1:v1_go_proto'
```

It wasn't related to the directive I added, but more to some gazelle defaults being overridden here: https://github.com/bazel-contrib/bazel-gazelle/blob/493e9d9072eace799138d5cc1188f9e4dcb22061/internal/bzlmod/default_gazelle_overrides.bzl#L137-L139.

**However**, I think it's preferable, at this point in time, to disable proto generation globally for external dependencies, rather than listing them explicitly:
- The existing native go toolchain based tooling imports code directly, doesn't generate protos, so we know we don't need to generate protos and that actually generating them could be an actual change.
- It's going to be painful not only for ourselves, but for colleagues outside of the build team that may add a dependency, come across a similar error, and be at a loss as for what to do.

It's always possible to opt in for specific deps, and we can revisit this further down the line. For now, I think this is the right call.

### Describe how you validated your changes

Passing CI.

### Additional Notes

Adding default attributes fully override gazelle's "by path" defaults included in https://github.com/bazel-contrib/bazel-gazelle/blob/493e9d9072eace799138d5cc1188f9e4dcb22061/internal/bzlmod/default_gazelle_overrides.bzl#L27.
Most of these are `proto disable`, a few are other things. I don't think relying on a pre-existing list of directives like that makes sense – 3rd party deps may change at any time and these directives are not pinned to specific upstream versions.

Co-authored-by: alex.lopez <alex.lopez@datadoghq.com>